"""add-process-columns-in-all-relations

Revision ID: 12e1f0297e3c
Revises: 8aedadd82b25
Create Date: 2025-04-19 22:30:11.327836

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12e1f0297e3c'
down_revision: Union[str, None] = '8aedadd82b25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('consumer_logs', sa.Column('is_analytics_processed', sa.Boolean(), nullable=False))
    op.add_column('kafka_batch_stats', sa.Column('is_rl_processed', sa.Boolean(), nullable=False))
    op.add_column('producer_logs', sa.Column('is_analytics_processed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('producer_logs', 'is_analytics_processed')
    op.drop_column('kafka_batch_stats', 'is_rl_processed')
    op.drop_column('consumer_logs', 'is_analytics_processed')
    # ### end Alembic commands ###
