"""alter-table-kafka-batch-stats-change-acks-data-type

Revision ID: 7b10ffe458a7
Revises: 12e1f0297e3c
Create Date: 2025-04-20 02:18:32.743715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b10ffe458a7'
down_revision: Union[str, None] = '12e1f0297e3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'kafka_batch_stats',
        'average_acks',
        existing_type=sa.Float(),  # Or sa.Numeric() depending on previous type
        type_=sa.String(length=10),
        postgresql_using="average_acks::text"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'kafka_batch_stats',
        'average_acks',
        existing_type=sa.String(length=10),
        type_=sa.Float(),
        postgresql_using="average_acks::double precision"
    )
    # ### end Alembic commands ###
